[package]
name = "rango-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["sqlite"]
sqlite = ["dep:sea-orm"]

[dependencies]
sea-orm = { workspace = true, optional = true, default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
chrono.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }