[workspace]
resolver = "3"
members = [
    "rango",
    "rango-admin",
    "rango-authentication",
    "rango-core",
    "rango-macros",
    "rango-store",
    "examples/helloworld",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
rango = { path = "rango", version = "0.1.0" }
rango-admin = { path = "rango-admin", version = "0.1.0" }
rango-authentication = { path = "rango-authentication", version = "0.1.0" }
rango-core = { path = "rango-core", version = "0.1.0" }
rango-macros = { path = "rango-macros", version = "0.1.0" }
rango-store = { path = "rango-store", version = "0.1.0", default-features = false }

axum = { version = "0.8.9", features = ["form", "json"] }
askama = "0.16.1"
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.7.1", features = ["fs", "trace", "catch-panic"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
chrono = "0.4"
rust_decimal = "1"
uuid = { version = "1.11", features = ["v4"] }
sea-orm = { version = "1", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"