[package]
name = "rango-web"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "A Django-like web framework for Rust with models, routing, templates, authentication, admin, and a CLI"
keywords = ["web", "framework", "django", "models", "store"]
categories = ["web-programming"]

[lib]
name = "rango"

[dependencies]
rango-core.workspace = true
rango-store.workspace = true
rango-admin.workspace = true
rango-authentication.workspace = true
tokio.workspace = true
tracing.workspace = true
rpassword = "7"