[package]
name = "rango-authentication"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["views"]
views = ["dep:askama"]

[dependencies]
rango-core.workspace = true
axum.workspace = true
bcrypt = "0.17"
hmac = "0.12"
sha2 = "0.10"
serde_urlencoded.workspace = true
askama = { workspace = true, optional = true }
